### ISSUE TITLE
No attribute error message during play

### ISSUE THREAD

**Issue by scottfurry** [shlomif/PySolFC#129]
Traceback during game play:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib64/python3.6/site-packages/pysollib/stack.py", line 1197, in __releaseEventHandler
    self.finishDrag(event)
  File "/usr/lib64/python3.6/site-packages/pysollib/stack.py", line 1554, in finishDrag
    self._stopDrag()
  File "/usr/lib64/python3.6/site-packages/pysollib/stack.py", line 1540, in _stopDrag
    for s in drag.shadows:
AttributeError: 'GameDrag' object has no attribute 'shadows'
```
Message popped up in console half dozen times during play of Klondike game type.

**Comment by shlomif** [comment]
@scottfurry : thanks for the report, Please try latest git master.

**Comment by scottfurry** [comment]
Looks like you got both this and #130.
Command line is nice and quiet again.
(insert cheering crowd) -> \o/ \0/ \O/

**Comment by shlomif** [comment]
@scottfurry : thanks for the update.
