### ISSUE TITLE
Missing library reference in setup.py

### ISSUE THREAD

**Issue by scottfurry** [shlomif/PySolFC#130]
Building from git latest and installing, attempt to start game would halt with the error message:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/pysol.py", line 41, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib64/python3.6/site-packages/pysollib/main.py", line 418, in main
    r = pysol_init(app, args)
  File "/usr/lib64/python3.6/site-packages/pysollib/main.py", line 237, in pysol_init
    import pysollib.games
  File "/usr/lib64/python3.6/site-packages/pysollib/games/__init__.py", line 23, in <module>
    from . import acesup  # noqa: F401
  File "/usr/lib64/python3.6/site-packages/pysollib/games/acesup.py", line 23, in <module>
    from pysollib.game import Game
ModuleNotFoundError: No module named 'pysollib.game'
```
Able to trace problem to missing `pysollib/game` file. Confirmed that files in question were missing from installed. A check of the `setup.py` confirmed that `pysollib.game` is not installed during setup. Fixed locally with:
```
diff --git a/setup.py b/setup.py
index 5a2c666..3e98eb7 100644
--- a/setup.py
+++ b/setup.py
@@ -91,6 +91,7 @@ kw = {
                  'pysollib.ui',
                  'pysollib.ui.tktile',
                  'pysollib.kivy',
+                 'pysollib.game',
                  'pysollib.games',
                  'pysollib.games.special',
                  'pysollib.games.ultra',
```

**Comment by shlomif** [comment]
Fixed, thanks!
