### ISSUE TITLE
[Android 7.1.2] Game crashes when playing Pyramid and Relaxed Pyramid

### ISSUE THREAD

**Issue by qunka** [shlomif/PySolFC#147]
When I start playing Pyramid or Relaxed Pyramid on Android, after a few seconds the application crashes. I get the below log from ADB:

```12-30 16:50:48.939 29975 29994 I python  : [INFO   ] [LTkBase     ] wait condition start
12-30 16:50:49.179 29975 29994 I python  : [INFO   ] [LApp        ] size changed <kivy.core.window.window_sdl2.WindowSDL object at 0xd6880298> - (1280, 720) ([1280, 720])
12-30 16:50:49.230 29975 29994 I python  : [INFO   ] [LApp        ] delayedRebuild
12-30 16:50:49.256 29975 29994 I python  : Sound: stopped, <kivy.core.audio.audio_sdl2.SoundSDL2 object at 0xd4bdc618>
12-30 16:50:49.293 29975 29994 I python  : [INFO   ] [LTkBase     ] wait condition end
12-30 16:50:49.294 29975 29994 I python  : updateBookmarkMenuState - fake
12-30 16:50:49.296 29975 29994 I python  : [INFO   ] [Base        ] Leaving application in progress...
12-30 16:50:49.300 29975 29994 I python  :  Traceback (most recent call last):
12-30 16:50:49.300 29975 29994 I python  :    File "/home/vagrant/.cache/tmp-for-p4a/pysolfc/src/main.py", line 37, in <module>
12-30 16:50:49.301 29975 29994 I python  :    File "/home/vagrant/.cache/tmp-for-p4a/pysolfc/src/pysollib/main.py", line 412, in main
12-30 16:50:49.301 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/app.py", line 855, in run
12-30 16:50:49.302 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/base.py", line 504, in runTouchApp
12-30 16:50:49.302 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/core/window/window_sdl2.py", line 746, in mainloop
12-30 16:50:49.303 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/core/window/window_sdl2.py", line 478, in _mainloop
12-30 16:50:49.303 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/base.py", line 342, in idle
12-30 16:50:49.304 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/base.py", line 327, in dispatch_input
12-30 16:50:49.304 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/base.py", line 233, in post_dispatch_input
12-30 16:50:49.305 29975 29994 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 16:50:49.305 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/core/window/__init__.py", line 1378, in on_motion
12-30 16:50:49.306 29975 29994 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 16:50:49.306 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/core/window/__init__.py", line 1394, in on_touch_down
12-30 16:50:49.307 29975 29994 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 16:50:49.307 29975 29994 I python  :    File "/home/vagrant/.cache/tmp-for-p4a/pysolfc/src/pysollib/kivy/LApp.py", line 1626, in on_touch_down
12-30 16:50:49.308 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/uix/widget.py", line 549, in on_touch_down
12-30 16:50:49.308 29975 29994 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 16:50:49.309 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/uix/widget.py", line 549, in on_touch_down
12-30 16:50:49.309 29975 29994 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 16:50:49.310 29975 29994 I python  :    File "/home/vagrant/.local/share/python-for-android/build/python-installs/pysolfc/kivy/uix/widget.py", line 549, in on_touch_down
12-30 16:50:49.311 29975 29994 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 16:50:49.311 29975 29994 I python  :    File "/home/vagrant/.cache/tmp-for-p4a/pysolfc/src/pysollib/kivy/LApp.py", line 748, in on_touch_down
12-30 16:50:49.312 29975 29994 I python  :    File "/home/vagrant/.cache/tmp-for-p4a/pysolfc/src/pysollib/kivy/LApp.py", line 718, in send_event_pressed_1
12-30 16:50:49.312 29975 29994 I python  :    File "/home/vagrant/.cache/tmp-for-p4a/pysolfc/src/pysollib/stack.py", line 1133, in __clickEventHandler
12-30 16:50:49.313 29975 29994 I python  :    File "/home/vagrant/.cache/tmp-for-p4a/pysolfc/src/pysollib/stack.py", line 1109, in __defaultClickEventHandler
12-30 16:50:49.313 29975 29994 I python  :  TypeError: '<=' not supported between instances of 'NoneType' and 'int'
12-30 16:50:49.313 29975 29994 I python  : Python for android ended.
```

I'm using PySolFC 2.6.4 from F-Droid.

**Comment by lufebe16** [comment]
Playing that game produces many python warnings and errors, also when running on Linux. Something is wrong with it. The difference between android and linux is the crash of former on "TypeError: '<=' not supported between instances of 'NoneType' and 'int'", wheras the linux version keeps calm.

**Comment by qunka** [comment]
Interesting. It seems the error is specifically triggered whenever the player clicks on the talon. Changing rows 1109-1111 in stack.py to:

```
            #if r <= 0:
            sound = r == 0
            self.startDrag(event, sound=sound)
```

fixes the problem, but I don't know enough about the code to tell you why, or whether it will have consequences elsewhere in the program. I'll see what @shlomif thinks. Perhaps we should ask the original author of PySol?

**Comment by lufebe16** [comment]
The actual problem here was (@qunka) that the handler didn't return an int value as it should. To remove simply the condition that failes in a common software part would mean to hurt all other 999 games.

**Comment by qunka** [comment]
My apologies.
