### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by mlmatlock** [shlomif/PySolFC#154]
OS: Arch
Kernel: 5.5.7
pysolfc:  2.8.0
python:  3.8.1

Upgraded from 2.6.4 to 2.8.0 today.  Starting pysol results in this:
```
$ pysol
Traceback (most recent call last):
  File "/usr/bin/pysol", line 36, in <module>
    from pysollib.main import main  # noqa: E402,I202
  File "/usr/lib/python3.8/site-packages/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/usr/lib/python3.8/site-packages/pysollib/app.py", line 45, in <module>
    from pysollib.options import Options
  File "/usr/lib/python3.8/site-packages/pysollib/options.py", line 28, in <module>
    import configobj
ModuleNotFoundError: No module named 'configobj'
```
 Returning (downgrading) to 2.6.4, and pysol starts normally.

**Comment by mlmatlock** [comment]
Disregard this post.  Problem was in my environment (missing a couple of supporting packages).  Once they were installed, Pysol works fine again.
