### ISSUE TITLE
pysolfc fails on Mint21 : "No module named formatter"

### ISSUE THREAD

**Issue by janert** [shlomif/PySolFC#267]
Running pysolfc on Linux Mint21 (Vanessa) fails - complete stacktrace below.
Root cause: "ModuleNotFoundError: No module named 'formatter'"

I looked at the source. The file htmllib2.py tries to import the formatter module.
This module has been deprecated since Python 3.4, and has apparently been
removed in Python 3.10. 

Complete stack trace follows.

Traceback (most recent call last):
  File "/usr/games/pysolfc", line 36, in <module>
    from pysollib.main import main  # noqa: E402,I202
  File "/usr/share/games/pysolfc/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/usr/share/games/pysolfc/pysollib/app.py", line 32, in <module>
    from pysollib.images import Images, SubsampledImages
  File "/usr/share/games/pysolfc/pysollib/images.py", line 28, in <module>
    from pysollib.pysoltk import copyImage, createBottom, createImage, loadImage
  File "/usr/share/games/pysolfc/pysollib/pysoltk.py", line 35, in <module>
    from pysollib.tile.tkhtml import *  # noqa: F401,F403
  File "/usr/share/games/pysolfc/pysollib/tile/tkhtml.py", line 29, in <module>
    from pysollib.ui.tktile.tkhtml import Base_HTMLViewer
  File "/usr/share/games/pysolfc/pysollib/ui/tktile/tkhtml.py", line 24, in <module>
    import formatter
ModuleNotFoundError: No module named 'formatter'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_games_pysolfc_pysol.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/games/pysolfc", line 36, in <module>
    from pysollib.main import main  # noqa: E402,I202
  File "/usr/share/games/pysolfc/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/usr/share/games/pysolfc/pysollib/app.py", line 32, in <module>
    from pysollib.images import Images, SubsampledImages
  File "/usr/share/games/pysolfc/pysollib/images.py", line 28, in <module>
    from pysollib.pysoltk import copyImage, createBottom, createImage, loadImage
  File "/usr/share/games/pysolfc/pysollib/pysoltk.py", line 35, in <module>
    from pysollib.tile.tkhtml import *  # noqa: F401,F403
  File "/usr/share/games/pysolfc/pysollib/tile/tkhtml.py", line 29, in <module>
    from pysollib.ui.tktile.tkhtml import Base_HTMLViewer
  File "/usr/share/games/pysolfc/pysollib/ui/tktile/tkhtml.py", line 24, in <module>
    import formatter
ModuleNotFoundError: No module named 'formatter'

**Comment by janert** [comment]
Just noticed that this is a duplicate of issue 253. 
Sorry for the spam.

**Comment by joeraz** [comment]
Yes, this has been reported multiple times.  However, it has already been fixed as of PySolFC 2.14.  Older versions of PySolFC are not compatible with Python 3.10.  In order to fix this, you'll either need to upgrade your version of PySolFC to 2.14 or newer, or downgrade Python to 3.9.

I think some of the people maintaining the packages for the Linux distributions are behind with their PySolFC packages.  I'd suggest reporting this to the people responsible for the Mint application bundles, as I only maintain the ones we have on the official site.
