### ISSUE TITLE
PySol ignores Alt+F4 hotkey

### ISSUE THREAD

**Issue by ssokolow** [shlomif/PySolFC#274]
If PySol obeys Ctrl+Q to quit, it should also obey the much more commonly supported Alt+F4, but, on the current git HEAD (7f0c6e18ec6eae494feb5229f12dbf26510071b6), that key combination has no visible effect.

**Comment by joeraz** [comment]
The ALT+F4 keybinding usually comes from the operating system level.  I'll have to test to see if adding it in the app level causes any conflicts.

**Comment by ssokolow** [comment]
What Google is bringing me suggests it should be handled automatically, similar to how Qt, GTK, etc handle it, same as if you click the close button in the titlebar, so I'm wondering if something is hooking it and overriding the behaviour.

**Comment by ssokolow** [comment]
Never mind. I just tried creating a minimal empty window and that doesn't respond either. Maybe it's necessary to check for non-macOS POSIX and manually implement it.

**Comment by ssokolow** [comment]
Something like this, maybe?

```python
import os, platform
import tkinter as tk


def quit(_):
    root.destroy()

root = tk.Tk()

if os.name == 'posix' and platform.system() != 'Darwin':
    root.bind('<Alt-F4>', quit)
root.mainloop()
```

**Comment by joeraz** [comment]
Can you try the potential fix in this fork, and let me know if this works: https://github.com/joeraz/PySolFC/tree/feature/altf4

**Comment by ssokolow** [comment]
Unfortunately not.

```
Traceback (most recent call last):
  File "pysol.py", line 41, in <module>
    sys.exit(main(sys.argv))
  File "/home/ssokolow/src/PySolFC_flatpak/altf4/pysollib/main.py", line 441, in main
    app.mainloop()
  File "/home/ssokolow/src/PySolFC_flatpak/altf4/pysollib/app.py", line 185, in mainloop
    approc = self.mainproc()  # setup process
  File "/home/ssokolow/src/PySolFC_flatpak/altf4/pysollib/app.py", line 354, in mainproc
    self.menubar = PysolMenubar(self, self.top,
  File "/home/ssokolow/src/PySolFC_flatpak/altf4/pysollib/actions.py", line 86, in __init__
    PysolMenubarTk.__init__(self, app, top, progress)
  File "/home/ssokolow/src/PySolFC_flatpak/altf4/pysollib/tile/menubar.py", line 48, in __init__
    PysolMenubarTkCommon.__init__(self, app, top, progress)
  File "/home/ssokolow/src/PySolFC_flatpak/altf4/pysollib/ui/tktile/menubar.py", line 197, in __init__
    self._createMenubar()
  File "/home/ssokolow/src/PySolFC_flatpak/altf4/pysollib/ui/tktile/menubar.py", line 865, in _createMenubar
    self._bindKey('Alt', 'F4', self.mQuit)
  File "/home/ssokolow/src/PySolFC_flatpak/altf4/pysollib/ui/tktile/menubar.py", line 873, in _bindKey
    bind(self.top, sequence, func)
  File "/home/ssokolow/src/PySolFC_flatpak/altf4/pysollib/ui/tktile/tkutil.py", line 191, in bind
    funcid = widget.bind(sequence, func)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1392, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1346, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: bad event type or keysym "AltKeyPress"
```

**Comment by joeraz** [comment]
I think I see what I did wrong.  Can you re-pull that branch and try once more?

**Comment by ssokolow** [comment]
Seems to work as it should now.

**Comment by joeraz** [comment]
Merged then.  Thanks,
