### ISSUE TITLE
Local Kivy version crashes

### ISSUE THREAD

**Issue by joeraz** [shlomif/PySolFC#310]
Trying to run the local Kivy version of PySolFC (ran python pysol.py --kivy) to confirm if recent changes broke anything on Android.  Had an error running it.  The app started and dealt the initial game, before crashing with an error.  The ultimate error is as follows:

Traceback (most recent call last):
   File "pysol.py", line 41, in <module>
     sys.exit(main(sys.argv))
   File "/home/joe/PySolFC/pysollib/main.py", line 430, in main
     KivyApp(args).run()
   File "/home/joe/.local/lib/python3.9/site-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/home/joe/.local/lib/python3.9/site-packages/kivy/app.py", line 949, in _run_prepare
     self.dispatch('on_start')
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/home/joe/PySolFC/pysollib/kivy/LApp.py", line 1849, in on_start
     requestStoragePerm()
   File "/home/joe/PySolFC/pysollib/kivy/androidperms.py", line 66, in requestStoragePerm
     logging.info("androidperms: API version %d" % (ap.version.SDK_INT))
 AttributeError: 'AndroidPerms' object has no attribute 'version'

Noticed this happening in both a Windows and Debian test environment, using a couple different versions of Python.

@lufebe16 - Is this related to your recent updates?  Is there a new method I should use for testing?

**Comment by lufebe16** [comment]
Its a bug: Some checks are missing. This part of code should only be called with an android device. I'll correct it soon.
Thanks for the hint.

**Comment by joeraz** [comment]
It works now, thanks.
