### ISSUE TITLE
Pysol not starting after system update

### ISSUE THREAD

**Issue by bjarkih1977** [shlomif/PySolFC#328]
I'm running Manjaro Kernel 5.15 and after running system upgrade/update this weekend the game doesn't start anymore.  Here's the output of pysol in terminator:
"Traceback (most recent call last):
  File "/usr/bin/pysol", line 36, in <module>
    from pysollib.main import main  # noqa: E402,I202
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/usr/lib/python3.11/site-packages/pysollib/app.py", line 32, in <module>
    from pysollib.actions import PysolMenubar
  File "/usr/lib/python3.11/site-packages/pysollib/actions.py", line 28, in <module>
    from pysollib.help import help_about, help_html
  File "/usr/lib/python3.11/site-packages/pysollib/help.py", line 29, in <module>
    from pysollib.pysoltk import HTMLViewer
  File "/usr/lib/python3.11/site-packages/pysollib/pysoltk.py", line 28, in <module>
    from pysollib.ui.tktile.tkutil import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pysollib/ui/tktile/tkutil.py", line 250, in <module>
    class PIL_Image(ImageTk.PhotoImage):
  File "/usr/lib/python3.11/site-packages/pysollib/ui/tktile/tkutil.py", line 291, in PIL_Image
    def resize(self, xf, yf, resample=Image.ANTIALIAS):
                                      ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
"
What am I to do?

**Comment by joeraz** [comment]
The issue you're describing is #323, which is a result of changes in Pillow 10.0.  It has been fixed and released in PySolFC version 2.21.0.

To resolve the issue, update your copy of PySolFC to 2.21.0 or downgrade Pillow to 9.5 or older.  If you're getting your copy of PySolFC from your Linux distribution's package manager, you should contact them and ask them to update the package.

**Comment by bjarkih1977** [comment]
Thank you @joeraz this solved the issue.

**Comment by joeraz** [comment]
Great!
