### ISSUE TITLE
crashing at startup

### ISSUE THREAD

**Issue by RichCat6** [shlomif/PySolFC#329]
Every time I start PySolFC on my computer, it crashes.
When I run it in terminal, it says:
Traceback (most recent call last):
File "usr/games/pysolfc", line 36, in <module>
from pysollib.main import main # noqa: E402,I202
File "/usr/share/games/pysolfc/pysollib/main.py", line 30, in <module>
from pysollib.app import Application
File "/usr/share/games/pysolfc/pysollib/app.py", line 32, in <module>
from pysollib.images import Images, SubsampledImages
File "/usr/share/games/pysolfc/pysollib/images.py", line 28, in <module>
from pysollib.pysoltk import copyImage, createBottom, createImage, loadImage
File "/usr/share/games/pysolfc/pysollib/pysoltk.py", line 35, in <module>
from pysollib.tile.tkhtml import * # noqa: F401,F403
File "/usr/share/games/pysolfc/pysollib/tile/tkhtml.py", line 29, in <module>
from pysollib.ui.tktile.tkhtml import Base_HTMLViewer
File "/usr/share/games/pysolfc/pysollib/ui/tktile/tkhtml.py", line 24, in <module>
import formatter
ModuleNotFoundError: No module named 'formatter'

Steps to reproduce:
- Try to launch the game

PySolFC version: 2.6.4

System Specs if required:
Sony VAIO VPCEB35FX
Intel Core i3 M370
4GB RAM
1tb Toshiba HDD
Xubuntu 22.04

**Comment by joeraz** [comment]
Versions of PySolFC prior to 2.14.0 are not compatible with Python 3.10 (see https://pysolfc.sourceforge.io/faq.html).  To resolve this issue, update PySolFC to 2.14.0 or later, or downgrade your copy of Python to 3.9 or older.  You can also get the latest version of PySolFC from Flathub.

If you received your copy of PySolFC from your Linux distribution's package manager, you should contact them about updating the package.
