### ISSUE TITLE
runtime error in all_games_html

### ISSUE THREAD

**Issue by lufebe16** [shlomif/PySolFC#352]
@joeraz 
Wenn building the apk ./buidozer.init is run
I get the following exception:

```
+ make rules
cd html-src && ./gen-html.py
cp -r html-src/images html-src/html
rm -rf data/html
mv html-src/html data
+ make all_games_html
cd html-src && ./gen-html.py
cp -r html-src/images html-src/html
rm -rf data/html
mv html-src/html data
cd data/html && /home/lb/PRG/Python/Kivy/github/PySolFC/scripts/all_games.py html id rules > all_games.html
Traceback (most recent call last):
  File "/home/lb/PRG/Python/Kivy/github/PySolFC/scripts/all_games.py", line 284, in <module>
    create_html(sort_by)
  File "/home/lb/PRG/Python/Kivy/github/PySolFC/scripts/all_games.py", line 199, in create_html
    all_games(sort_by)
  File "/home/lb/PRG/Python/Kivy/github/PySolFC/scripts/all_games.py", line 154, in all_games
    gt = 'French (%s)' % GAME_BY_TYPE[gi.si.game_type]
                         ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 41
make: *** [Makefile:32: data/html/all_games.html] Fehler 1
(
```
It is located in scripts/all_games_html.py. Was introduced around
Nov. 19.

**Comment by joeraz** [comment]
Could you try it again?  I added the missing types to that script.

**Comment by lufebe16** [comment]
Thanks
