### ISSUE TITLE
File -> "Save as" stopped working on the git master

### ISSUE THREAD

**Issue by shlomif** [shlomif/PySolFC#39]
File → "Save as" stopped working properly and throws this exception:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "/home/shlomif/Download/unpack/games/pysolfc/git/PySolFC/pysollib/ui/tktile/menubar.py", line 1223, in mSaveAs
    d = tkinter_filedialog.SaveAs()
AttributeError: 'module' object has no attribute 'SaveAs'

```

**Comment by shlomif** [comment]
Fixed in https://github.com/shlomif/PySolFC/commit/763477d2188ce1c2f9fae73bc1e529aa98fda64f . Closing.
