### ISSUE TITLE
Running pysolfc in kubuntu 24.04 CTD 

### ISSUE THREAD

**Issue by allenwrench300** [shlomif/PySolFC#402]
Traceback (most recent call last):
  File "/usr/games/pysolfc", line 36, in <module>
    from pysollib.main import main  # noqa: E402,I202
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/games/pysolfc/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/usr/share/games/pysolfc/pysollib/app.py", line 31, in <module>
    from pysollib.gamedb import GAME_DB, GI, loadGame
  File "/usr/share/games/pysolfc/pysollib/gamedb.py", line 25, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

Kubuntu 24.04

**Comment by joeraz** [comment]
Please confirm that you're using the latest version of PySolFC (3.1.0).  I believe the import statement with the error was removed in the last release.

**Comment by allenwrench300** [comment]
> Please confirm that you're using the latest version of PySolFC (3.1.0). I believe the import statement with the error was removed in the last release.

oops kubuntu has the older version, 2.6.4-3 am installing it from flatpak and/or snap. sorry ill close this
